version: 2 
updates: 
  - package-ecosystem: "pip"
    directory: "/backend/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
#default open pull request limit is 5
  - package-ecosystem: "npm"
    directory: "frontend"
    schedule: 
      interval: "weekly"
    open-pull-requests-limit: 10