# app/db_init.py - Database initialization and schema setup
from flask import current_app
from app.raw_db import connect
import os
import logging

logger = logging.getLogger(__name__)

def create_users_table():
    """
    Create the users table as specified in the requirements with citext extension.
    This is idempotent and won't fail if the table already exists.
    """
    conn = connect()
    try:
        with conn.cursor() as cur:
            # Enable citext extension
            cur.execute("CREATE EXTENSION IF NOT EXISTS citext;")
            
            # Create users table
            cur.execute("""
                CREATE TABLE IF NOT EXISTS users (
                    user_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    email             CITEXT NOT NULL UNIQUE,
                    password_hash     TEXT,
                    email_verified_at TIMESTAMP WITH TIME ZONE,
                    last_login        TIMESTAMP WITH TIME ZONE,
                    joined_at         TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
                    is_active         BOOLEAN DEFAULT TRUE NOT NULL
                );
            """)
            
            conn.commit()
            logger.info("Users table created successfully")
    except Exception as e:
        conn.rollback()
        logger.error(f"Error creating users table: {e}")
        raise
    finally:
        conn.close()

def init_database():
    """Initialize the database with required tables and extensions."""
    try:
        create_users_table()
        logger.info("Database initialization completed")
    except Exception as e:
        logger.error(f"Database initialization failed: {e}")
        raise